name: benchmark on main branch

on:
  push:
    branches:
      - never

jobs:
  runBenchmark:
    name: run benchmark
    runs-on: benchmarks
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run benchmarks
        run: cargo bench
